Adding securityContext options at the pod and container level.
fluxcd/helm-operator pull request #494
Opened 2020-07-21 18:12 UTC by swade1987

Allowing the configuration of `SecurityContext` at the pod and individual container levels.

2020-07-29 22:46 UTC, saada commented
The tests seem to be failing.
`# Error: Error: Reading chart 'helm-operator' default values (# Default values for helm-operator`.
Not sure why...

2020-07-29 22:46 UTC, saada commented
`# ): error converting YAML to JSON: yaml: line 243: did not find expected key`

2020-07-29 22:47 UTC, saada commented
```yaml
containerSecurityContext: {}
  helmOperator: {}
  tiller: {}
```

needs to be change to
```yaml
containerSecurityContext:
  helmOperator: {}
  tiller: {}
```

2020-07-29 22:53 UTC, saada requested changes

2020-07-29 22:53 UTC, saada commented on chart/helm-operator/templates/deployment.yaml
> +{{ toYaml .Values.securityContext | indent 12 }}
I think this should be `| indent: 8` ?

2020-07-29 22:53 UTC, saada commented on chart/helm-operator/templates/deployment.yaml
> +{{ toYaml .Values.containerSecurityContext.helmOperator | indent 12 }}
I think this should be `| indent: 10` ?

2020-07-29 22:53 UTC, saada commented on chart/helm-operator/templates/deployment.yaml
> + {{ toYaml .Values.containerSecurityContext.tiller | indent 12 }}
I think this should be `| indent: 10` ?

2020-07-29 22:53 UTC, saada commented on chart/helm-operator/values.yaml
> +containerSecurityContext: {}
please remove `{}` here

2020-07-29 22:58 UTC, saada commented
Thanks for contributing! Just a few pointers to get these tests passing

2020-07-30 20:13 UTC, saada commented
@hiddeco can we rerun tests?

2020-07-30 20:14 UTC, hiddeco commented
Rebasing and force-pushing will trigger a new build while also getting rid of the `Merge branch 'master' into master` commit.

2020-07-31 12:44 UTC, hiddeco commented on chart/helm-operator/Chart.yaml
> +version: 1.1.1
FYI: we do not bump versions on changes, but bump it on release.

2020-07-31 13:53 UTC, hiddeco approved these changes
Thanks @swade1987 :tulip:

2020-07-31 13:54 UTC, merged