Allow for deploying Tiller as a sidecar.
fluxcd/helm-operator pull request #79
Opened 2019-10-20 18:11 UTC by bmcstdio

In this PR I propose adding support in the Helm chart for deploying Tiller as a sidecar (restricted to `localhost`). This is inspired by a [comment](https://github.com/fluxcd/flux/issues/1420#issuecomment-426759442) by @justinbarrick, and I believe that, although possibly being an advanced scenario, would be of use for some people ( like me 🙂 ). Tiller is eventually going away, but I believe this may be a useful addition while #8 isn't finished. I've kept this new feature undocumented because it's probably a good idea to "restrict" access to it to whoever finds themselves in need of fiddling with `values.yaml` ( and also because I am not quite sure this will get accepted as a feature 🙂 ).

2019-10-20 18:13 UTC, bmcstdio commented
As a side note, I think this may also be of use to whoever justs wants to try `helm-operator` without having to deploying any other piece of infrastructure.

2019-10-21 08:40 UTC, stefanprodan requested changes

2019-10-21 08:40 UTC, stefanprodan commented on chart/helm-operator/templates/deployment.yaml
> +          value: "0"
```suggestion
          value: "10"
```
Change the max history setting according to our docs https://docs.fluxcd.io/projects/helm-operator/en/latest/tutorials/get-started.html

2019-10-21 08:40 UTC, stefanprodan commented on chart/helm-operator/values.yaml
> +    tag: v2.14.1
```suggestion
    tag: v2.14.3
```
Match https://github.com/fluxcd/helm-operator/blob/master/docker/helm.version

2019-10-21 08:51 UTC, bmcustodio commented
Thank you @stefanprodan, accepted both changes!

2019-10-21 08:59 UTC, stefanprodan requested changes
Please add the `tillerSidecar` fields to the chart readme.

2019-10-21 09:25 UTC, bmcstdio commented
@stefanprodan done!

2019-10-22 07:44 UTC, stefanprodan requested changes

2019-10-22 07:44 UTC, stefanprodan commented on chart/helm-operator/Chart.yaml
> +version: 0.3.0
Please undo this change, the version will be bumped when we do a Helm-op release

2019-10-22 07:47 UTC, stefanprodan approved these changes
LGTM

Thanks @bmcstdio

2019-10-22 07:58 UTC, merged

2019-11-14 18:55 UTC, dmccaffery commented
If you release this, I might give you a kiss when I meet you next.

O.o
o.O
O.O
>.<